### ISSUE TITLE
V 0.1.0 stop script got some error

### ISSUE THREAD

**Issue by wild-flame** [nginyc/rafiki#120]
I am currently at branch `V 0.1.0`. When I type 
```
$ bash scripts/stop.sh
```

I would got the following error message.

```
---------------------------------
| Stopping any existing jobs... |
---------------------------------
Traceback (most recent call last):
  File "./scripts/stop_all_jobs.py", line 3, in <module>
    from rafiki.client import Client
  File "/home/david/coding/rafiki/rafiki/rafiki/client/__init__.py", line 1, in <module>
    from .client import Client
  File "/home/david/coding/rafiki/rafiki/rafiki/client/client.py", line 17
    nonlocal msg
               ^
SyntaxError: invalid syntax

```

**Comment by nginyc** [comment]
Can you check the python version you're using when you type `python` on your command line?

**Comment by nginyc** [comment]
Refer to the docs on the requirement for `python` to point to a valid installation of Python 3.6 here: https://nginyc.github.io/rafiki/docs/0.1.0/src/user/installing-python.html

**Comment by wild-flame** [comment]
```
(rafiki) david@David-OptiPlex-5060:~/coding/rafiki/rafiki$ python --version
Python 3.6.8 :: Anaconda, Inc.
```

**Comment by wild-flame** [comment]
I guess I find out why, because when i use `sudo -E python`,

The version is 2.7.

```
(rafiki) david@David-OptiPlex-5060:~/coding/rafiki/rafiki$ sudo python --version
Python 2.7.15rc1
```

**Comment by wild-flame** [comment]
Solved it by link python3 to /usr/bin/python
