### ISSUE TITLE
have some trouble `create train job` use `model_id`

### ISSUE THREAD

**Issue by wild-flame** [nginyc/rafiki#123]
## Version/Branch

Dev

## what is the problem

model id get is `cfd73f10-583c-44e5-805b-8c8ca1151919`, however when I post it to server it  replied with `invaildModelError`

## get `models/available` 

```
[
    {
        "access_right": "PRIVATE",
        "datetime_created": "Tue, 18 Jun 2019 08:53:27 GMT",
        "dependencies": {
            "tensorflow": "1.12.0"
        },
        "id": "cfd73f10-583c-44e5-805b-8c8ca1151919",
        "name": "TfFeedForward3",
        "task": "IMAGE_CLASSIFICATION",
        "user_id": "32e8274f-6937-4fe6-84f1-afb96c11cc5a"
    },
    {
        "access_right": "PRIVATE",
        "datetime_created": "Tue, 18 Jun 2019 08:54:11 GMT",
        "dependencies": {
            "tensorflow": "1.12.0"
        },
        "id": "985d0c36-494e-4eec-b03f-d7f595ad7236",
        "name": "TfVgg16",
        "task": "IMAGE_CLASSIFICATION",
        "user_id": "32e8274f-6937-4fe6-84f1-afb96c11cc5a"
    }
]
```

## Then post `/train_jobs`

body

```
{ 
  "app": "fashion_mnist",
  "budget": {"MODEL_TRIAL_COUNT": "2"},
  "model_ids": ["cfd73f10-583c-44e5-805b-8c8ca1151919", "985d0c36-494e-4eec-b03f-d7f595ad7236"],
  "task": "IMAGE_CLASSFICATION",
  "train_dataset_id": "774c700e-0d56-4e3d-a385-310dbdfa99f3",
  "val_dataset_id": "f7237ac3-f08e-421c-91c6-1f85f7e88c19"
}
```

response

```
Traceback (most recent call last):
  File "/usr/local/envs/rafiki/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/envs/rafiki/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/rafiki/rafiki/utils/auth.py", line 42, in wrapped
    return f(auth, *args, **kwargs)
  File "/root/rafiki/rafiki/admin/app.py", line 148, in create_train_job
    return jsonify(admin.create_train_job(auth['user_id'], **params))
  File "/root/rafiki/rafiki/admin/admin.py", line 184, in create_train_job
    raise InvalidModelError('No model of ID "{}" is available'.format(model_id))
rafiki.admin.admin.InvalidModelError: No model of ID "cfd73f10-583c-44e5-805b-8c8ca1151919" is available
```

**Comment by nginyc** [comment]
You might have misspelled "IMAGE_CLASSIFICATION" while creating a train job. I will improve the error message

**Comment by wild-flame** [comment]
i see
